[package]
name = "hello-cardano"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.6"

serde = { version = "1", features = ["derive"] }
serde_json = "1"

primes = "0.3"
